interface Ingredient {
  name: string;
  image: string;
  category: string;
}

// Add a `category` property to each element in this array
export const ingredients: Ingredient[] = [
  { name: 'Avocado', image: 'https://spoonacular.com/cdn/ingredients_250x250/avocado.jpg', category: 'Fruits' },
  { name: 'Baking powder', image: 'https://spoonacular.com/cdn/ingredients_250x250/white-powder.jpg', category: 'Baking' },
  { name: 'Basil', image: 'https://spoonacular.com/cdn/ingredients_250x250/basil.jpg', category: 'Spices' },
  { name: 'Beef', image: 'https://spoonacular.com/cdn/ingredients_250x250/beef-cubes-raw.png', category: 'Meat' },
  { name: 'Bell peppers', image: 'https://spoonacular.com/cdn/ingredients_250x250/green-pepper.jpg', category: 'Vegetables' },
  { name: 'Bread', image: 'https://spoonacular.com/cdn/ingredients_250x250/white-bread.jpg', category: 'Grains' },
  { name: 'Broccoli', image: 'https://spoonacular.com/cdn/ingredients_250x250/broccoli.jpg', category: 'Vegetables' },
  { name: 'Butter', image: 'https://spoonacular.com/cdn/ingredients_250x250/butter.jpg', category: 'Dairy' },
  { name: 'Carrots', image: 'https://spoonacular.com/cdn/ingredients_250x250/carrots.jpg', category: 'Vegetables' },
  { name: 'Cheese', image: 'https://spoonacular.com/cdn/ingredients_250x250/cheddar-cheese.jpg', category: 'Dairy' },
  { name: 'Chicken', image: 'https://spoonacular.com/cdn/ingredients_250x250/chicken-breast.jpg', category: 'Meat' },
  { name: 'Chickpeas', image: 'https://spoonacular.com/cdn/ingredients_250x250/chickpeas.jpg', category: 'Legumes' },
  { name: 'Cocoa powder', image: 'https://spoonacular.com/cdn/ingredients_250x250/cocoa-powder.jpg', category: 'Baking' },
  { name: 'Coconut oil', image: 'https://spoonacular.com/cdn/ingredients_250x250/coconut-oil.jpg', category: 'Oils' },
  { name: 'Cumin', image: 'https://spoonacular.com/cdn/ingredients_250x250/cumin.jpg', category: 'Spices' },
  { name: 'Eggs', image: 'https://spoonacular.com/cdn/ingredients_250x250/egg.jpg', category: 'Dairy' },
  { name: 'Fish', image: 'https://spoonacular.com/cdn/ingredients_250x250/salmon.jpg', category: 'Seafood' },
  { name: 'Flour', image: 'https://spoonacular.com/cdn/ingredients_250x250/flour.jpg', category: 'Baking' },
  { name: 'Garlic', image: 'https://spoonacular.com/cdn/ingredients_250x250/garlic.jpg', category: 'Spices' },
  { name: 'Green beans', image: 'https://spoonacular.com/cdn/ingredients_250x250/soy-beans.jpg', category: 'Vegetables' },
  { name: 'Honey', image: 'https://spoonacular.com/cdn/ingredients_250x250/honey.jpg', category: 'Condiments' },
  { name: 'Ketchup', image: 'https://spoonacular.com/cdn/ingredients_250x250/ketchup.jpg', category: 'Spices' },
  { name: 'Lemon juice', image: 'https://spoonacular.com/cdn/ingredients_250x250/lemon-juice.jpg', category: 'Baking' },
  { name: 'Lettuce', image: 'https://spoonacular.com/cdn/ingredients_250x250/iceberg-lettuce.jpg', category: 'Vegetables' },
  { name: 'Lime juice', image: 'https://spoonacular.com/cdn/ingredients_250x250/lime-juice.jpg', category: 'Baking' },
  { name: 'Maple syrup', image: 'https://spoonacular.com/cdn/ingredients_250x250/maple-syrup.png', category: 'Baking' },
  { name: 'Mayonnaise', image: 'https://spoonacular.com/cdn/ingredients_250x250/mayonnaise.jpg', category: 'Condiments' },
  { name: 'Milk', image: 'https://spoonacular.com/cdn/ingredients_250x250/milk.jpg', category: 'Dairy' },
  { name: 'Mustard', image: 'https://spoonacular.com/cdn/ingredients_250x250/mustard.jpg', category: 'Condiments' },
  { name: 'Olive oil', image: 'https://spoonacular.com/cdn/ingredients_250x250/olive-oil.jpg', category: 'Oils' },
  { name: 'Onions', image: 'https://spoonacular.com/cdn/ingredients_250x250/red-onion.jpg', category: 'Vegetables' },
  { name: 'Oregano', image: 'https://spoonacular.com/cdn/ingredients_250x250/oregano.jpg', category: 'Spices' },
  { name: 'Parsley', image: 'https://spoonacular.com/cdn/ingredients_250x250/parsley.jpg', category: 'Spices' },
  { name: 'Pasta', image: 'https://spoonacular.com/cdn/ingredients_250x250/fusilli.jpg', category: 'Grains' },
  { name: 'Pepper', image: 'https://spoonacular.com/cdn/ingredients_250x250/pepper.jpg', category: 'Spices' },
  { name: 'Pork', image: 'https://spoonacular.com/cdn/ingredients_250x250/pork-tenderloin-raw.png', category: 'Meat' },
  { name: 'Potatoes', image: 'https://spoonacular.com/cdn/ingredients_250x250/potatoes-yukon-gold.png', category: 'Vegetables' },
  { name: 'Rice', image: 'https://spoonacular.com/cdn/ingredients_250x250/uncooked-white-rice.png', category: 'Grains' },
  { name: 'Rosemary', image: 'https://spoonacular.com/cdn/ingredients_250x250/rosemary.jpg', category: 'Spices' },
  { name: 'Salsa', image: 'https://spoonacular.com/cdn/ingredients_250x250/salsa.jpg', category: 'Condiments' },
  { name: 'Salt', image: 'https://spoonacular.com/cdn/ingredients_250x250/salt.jpg', category: 'Spices' },
  { name: 'Shrimp', image: 'https://spoonacular.com/cdn/ingredients_250x250/shrimp.jpg', category: 'Seafood' },
  { name: 'Soy sauce', image: 'https://spoonacular.com/cdn/ingredients_250x250/soy-sauce.jpg', category: 'Condiments' },
  { name: 'Spinach', image: 'https://spoonacular.com/cdn/ingredients_250x250/spinach.jpg', category: 'Vegetables' },
  { name: 'Sugar', image: 'https://spoonacular.com/cdn/ingredients_250x250/sugar-cubes.jpg', category: 'Baking' },
  { name: 'Thyme', image: 'https://spoonacular.com/cdn/ingredients_250x250/thyme.jpg', category: 'Spices' },
  { name: 'Tofu', image: 'https://spoonacular.com/cdn/ingredients_250x250/tofu.jpg', category: 'Vegetarian Protein' },
  { name: 'Tomatoes', image: 'https://spoonacular.com/cdn/ingredients_250x250/tomato.jpg', category: 'Vegetables' },
  { name: 'Vanilla extract', image: 'https://spoonacular.com/cdn/ingredients_250x250/vanilla-extract.jpg', category: 'Baking' },
  { name: 'Vegetable oil', image: 'https://spoonacular.com/cdn/ingredients_250x250/vegetable-oil.jpg', category: 'Oils' },
  { name: 'Vinegar', image: 'https://spoonacular.com/cdn/ingredients_250x250/vinegar-(white).jpg', category: 'Condiments' },
].sort((a, b) => a.name > b.name ? 1 : -1);

export default ingredients;
