name: Deploy to Heroku
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    defaults:
      run:
        working-directory: ./api
    runs-on: ubuntu-latest
    env: 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        run: heroku container:login

      - name: Build Docker image
        run: heroku container:push web -a chef-gpt

      - name: Release Docker image
        run: heroku container:release web -a chef-gpt
